project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Analyzing NYC's Payroll Data"
  author:
    - Ayon Roy (ar4982)
    - Rushil Patra (rp3325)
  repo-url: https://github.com/iAyon/EDAV
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: flatly
    code-fold: true


